language: php

jobs:
  include:
    - php: 7.1
        env: TYPE=phpstan
          install:
            - mkdir -p "$HOME/.phpstan"
            - composer require --dev phpstan/phpstan-shim --working-dir "$HOME/.phpstan"
          script:
            - composer install
            - vendor/bin/phpstan analyse
