language: php

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist


jobs:
  include:
    - php: 7.1
        name: phpstan
        script:
          - vendor/bin/phpstan analyse
